# Dependencies
markdown:         redcarpet
highlighter:         true
port: 8877

# Permalinks
permalink:        pretty

# Setup
title:            Vefforritun 2014
tagline:          Blog about Vefforitun
url:              http://tryggvigy.github.io
paginate:         1
baseurl:          /vefforritun
author:
  name:           Tryggvi Gylfason
  email:          tryggvigy@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole


pages_list:
  About: '/vefforritun/navPages/about'
  Archive: '/vefforritun/navPages/archive'
  Feed: '/vefforritun/navPages/atom.xml'

paths:
  dist:
    styles:
      main: '/vefforritun/dist/css/'

    js: '/vefforritun/dist/js/'

    static :
      img: '/vefforritun/dist/static/images/'
      font: '/vefforritun/dist/static/fonts/'

  navPages:
    base: '/vefforritun'
